version: '2'
services:
  app:
    build: .
    command: ["bin/rails", "server", "-p", "3000", "-b", "0.0.0.0"]
    env_file: .env
    environment:
      RAILS_ENV: development
      MYSQL_HOST: mysql
    ports:
      - '3100:3000'
    volumes:
      - .:/kintai
    links:
      - mysql
    volumes_from:
      - bundle

  mysql:
    image: 'mysql:5.7.17'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  bundle:
    image: kintai_app
    volumes:
      - /bundle
